// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClJYA3IT1KE1QkD21JJ2xD2b_un1YRA6Y',
    appId: '1:809581692431:web:9b0b1ed6dd91bd9c9e857a',
    messagingSenderId: '809581692431',
    projectId: 'flutter-chat-app-cd2f2',
    authDomain: 'flutter-chat-app-cd2f2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cd2f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRg7tOCQG_7Tfa9yigWL8h84a_o-eEzBc',
    appId: '1:809581692431:android:d9551bda253e5d069e857a',
    messagingSenderId: '809581692431',
    projectId: 'flutter-chat-app-cd2f2',
    storageBucket: 'flutter-chat-app-cd2f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdns612086oxNO4ySZ2XkDKaWb95e35mY',
    appId: '1:809581692431:ios:853341b7558b18cc9e857a',
    messagingSenderId: '809581692431',
    projectId: 'flutter-chat-app-cd2f2',
    storageBucket: 'flutter-chat-app-cd2f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdns612086oxNO4ySZ2XkDKaWb95e35mY',
    appId: '1:809581692431:ios:853341b7558b18cc9e857a',
    messagingSenderId: '809581692431',
    projectId: 'flutter-chat-app-cd2f2',
    storageBucket: 'flutter-chat-app-cd2f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClJYA3IT1KE1QkD21JJ2xD2b_un1YRA6Y',
    appId: '1:809581692431:web:b148245e7c8aad9e9e857a',
    messagingSenderId: '809581692431',
    projectId: 'flutter-chat-app-cd2f2',
    authDomain: 'flutter-chat-app-cd2f2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cd2f2.firebasestorage.app',
  );
}
